### PR TITLE
Need to change the color of Cards. #2

### PR DESCRIPTION
**Pull request by fletcherrippon**
Issue: Need to change the color of Cards. [#2](https://github.com/sabesansathananthan/github-readme-medium-card/issues/2)
------

Made a dark and light theme for the cards and made it easy to add/create other themes

### CODE REVIEW

**Review by ssat4805 — COMMENTED** [review]
This is the deployed link Theme not working and It is not like pinned repositories in Github

https://github-readme-medium-card-git-master.sabesansathananthan.vercel.app/getMediumBlogs?username=sabesan96&theme=dark&limit=6

**Comment by fletcherrippon** [comment]
You only said to make a theme I don't understand what you mean by pinned and the themes seems to work for me

**Comment by ssat4805** [comment]
Pinned repository means the below image... width height and border and curved corner for the cards. 

95682993-2aa92f80-0c06-11eb-825a-6297371c7d7b

**Comment by fletcherrippon** [comment]
gave it a border-radius and border

**Comment by ssat4805** [comment]
That issue was fixed and closed. I will close this PR

**Pull request closed without merging**
