### PR TITLE
Create a offset Parameter for Displaying a Single Item

### PR DESCRIPTION
**Pull request by gnanakeethan**
Add Offset Parameter For Singular Post Display

### CODE REVIEW

**Comment by ssat4805** [comment]
test  🚀

**Comment by gnanakeethan** [comment]
We need another edit. Wait

**Comment by gnanakeethan** [comment]
@sabesansathananthan fixed now.

**Comment by gnanakeethan** [comment]
Sabesan96's Medium Post
Sabesan96's Medium Post
Sabesan96's Medium Post

**Pull request merged**
