### PR TITLE
refactor: change async foreach to Promise map

### PR DESCRIPTION
**Pull request by bayungrh**

### CODE REVIEW

**Review by ssat4805 — COMMENTED** [review]
Why did you remove async and await ??? explain please

**Comment by bayungrh** [comment]
> Why did you remove async and await ??? explain please

If inside the function directly uses return you don't need to use await anymore, efficient and clean. You can try running it are the code still works?

**Comment by bayungrh** [comment]
Hi 

> > Why did you remove async and await ??? explain please
> 
> If inside the function directly uses return you don't need to use await anymore, efficient and clean. You can try running it are the code still works?

Hi @sabesansathananthan I've explained it. Thank's

**Comment by ssat4805** [comment]
we are now developing this application. For Now, We don't know what will be deleted and what will be not deleted.. So I think This PR no needed for Now. I will close this

**Pull request closed without merging**
