### PR TITLE
Implemented themes, custom colors, and two column layout.

### PR DESCRIPTION
**Pull request by Aynn**
I only added 3 themes - dark, light, and dracula. But adding a new theme is as simple as adding a new block to the switch statement in `blogCard.js`.

```
      case 'newThemeName':
        title_color = "#COLOR";
        text_color = "#COLOR";
        bg_color = "#COLOR";
        break;
```

There's also 3 new url parameters in case you want to define your own colors these are: `title_color`, `text_color`, and `bg_color`.
The theme parameter takes precedence over these.  #2

### CODE REVIEW

**Comment by ssat4805** [comment]
I was Really Impressed with your PR brother But Can we change some small modifications.
- [ ] Need to add a grey border for the light theme cards. and add a border for other cards with matching color schemes. 
- [ ]  Bold the heading
- [ ] heading is breaking meaningless. Need to correct.
- [ ] Increase the width and height of the card. (feel good if it is same as Github Pinned repo's width and height)
- [ ]   Increase the Medium Post's Image width.
- [ ] add a border-radius (~0.625rem) for cards. It means Need round corners for the cards. 
- [ ] In dark theme author's name and date of published are not visible 

Overall I liked your PR.. Very Impressive. Could you please consider the above issue? 
Herewith I attached the working model of your Implementation and GitHub Pinned Repos Image. If you have any doubts about the above suggestions feel free to contact me.  Mostly I active on Whatsapp +94770711017

ss
Capture


95682993-2aa92f80-0c06-11eb-825a-6297371c7d7b

**Comment by Aynn** [comment]
I would be happy to take a look at it once I get a chance, I am looking to do the hacktoberfest PRs so if you could merge these changes and set these improvements as a seperate request that would be great! 

Edit: Fixed the dark theme text for now.

**Comment by Aynn** [comment]
> * [x]  Need to add a grey border for the light theme cards. and add a border for other cards with matching color schemes.
> * [x]   Bold the heading
> * [ ]  heading is breaking meaningless. Need to correct.
> * [x]  Increase the width and height of the card. (feel good if it is same as Github Pinned repo's width and height)
> * [x]    Increase the Medium Post's Image width.
> * [x]  add a border-radius (~0.625rem) for cards. It means Need round corners for the cards.
> * [x]  In dark theme author's name and date of published are not visible

I have implemented the following changes, as per request. 
In addition to this I have externalized all values into a config file- this includes themes, as well as x, y values for the title, author, date, etc. This should allow for modification of the output without changing the code. 

Seems svg doesn't support text wrapping, I will look into a solution when I get a change. Closes: #2

**Comment by Aynn** [comment]
I have noticed a lot of overlap work on this issue - Please start pushing the changes and opening outstanding issues so everyone can participate in hacktoberfest.

**Comment by ssat4805** [comment]
Thank you for your PR I have many suggestions. For Now. I will accept it with hactoberfect-accept label.. don't worry.. best of luck with your hacktoberfest event... Don't forget to give a star

**Comment by ssat4805** [comment]
Capture

**Comment by Aynn** [comment]
@sabesansathananthan  

Thanks, you as well! I have attached the values that you can change in the config. 

The url parameters now are: `width, height, limit, bg_color, image_background, image_width, image_height, image_x, image_y, title_color, title_x, title_y, author_color, author_x, author_y, author_font_size, date_color, date_x, date_y, date_font_size`.

You can now mix and match theme + parameters, parameters will overwrite the themes value.

image

**Comment by ssat4805** [comment]
If you don't mind.. can I ask for some help from you??
Then we will publish this on each social media and start to reach it out...
If you watched the below-attached image. The post image is fit with the card and has a nice curved corner on the left side.
I forgot that If the card size is high the people Don't like to embed to their GitHub profile README. Therefore shall we reduce the height of the card like shown below image. Herewith I attached the link to that model. 

https://github-readme-medium-card-isujleous.vercel.app/getMediumBlogs?username=sabesan96&theme=dark


Capture

**Comment by Aynn** [comment]
image

**Review by ssat4805 — APPROVED** [review]
Thank you I am going to merge it

**Pull request merged**
